from t4c21.t4c_lightning_datamodule import T4CDataModule
from t4c21.t4c_lightning_system import T4CSystem

T4CDataModule.train_dataloader
T4CDataModule.val_dataloader
T4CDataModule.test_dataloader
T4CSystem.backward_parameters
T4CSystem.training_step
T4CSystem.validation_step
T4CSystem.test_step
T4CSystem.configure_optimizers
